"""Reproduction + audit tool for the PreCrop evidence data pack.

CONFIG constants, JSON I/O with pinned LF line endings, the
"precrop-canon-v1" canonicalisation + sha256 rule, evidence-report
assembly from the committed v2 pack files (data/lote-sentinel-presets.json,
data/demo-scenarios.json, data/photo-point-presets.json), and the Phase 4
reproduction layer: STAC search (by scene id) + SAS signing against
Microsoft Planetary Computer, a windowed rasterio read of B04/B08 over the
AOI bbox, offset-corrected NDVI stats, and Open-Meteo 7-day rain sums.

rasterio / pystac_client / planetary_computer / requests are intentionally
NOT imported at module scope -- each is imported LOCALLY inside the one
function that needs it, so `python scripts/build_pack.py --help`, the
offline `--only evidence` path, and the pytest suite that imports this
module all work on a machine with none of those packages installed. Only
`--write`, `--check` and `--only {ndvi,rain,assemble}` touch the network.

There is no `--fetch-photos` mode: the preset photos under
data/presets/fotos/ are owned by another track and are not generated by
this pack (see data/demo-scenarios.json photos_ownership_note).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"

# ---------------------------------------------------------------------------
# CONFIG - the only place constants live (per design)
# ---------------------------------------------------------------------------

AOI_BBOX = [-63.7254, -31.4245, -63.7146, -31.4155]
CENTER = {"lat": -31.42, "lon": -63.72}

SCENES = {
    "fecha_buena": "S2B_MSIL2A_20250202T140709_R110_T20JML_20250202T175010",
    "fecha_mala": "S2C_MSIL2A_20250207T140811_R110_T20JML_20250207T174511",
}

RAIN_WINDOWS = {
    "fecha_buena": {"start": "2025-01-27", "end": "2025-02-02"},
    "fecha_mala": {"start": "2025-02-01", "end": "2025-02-07"},
}

PINNED_WEEDS = {"bueno": 12, "mixto": 55, "malo": 65}

NDVI_FLOOR = 0.20
NDVI_CEILING = 0.85

WEIGHTS = {"ndvi_norm": 0.6, "climate": 0.25, "weeds_pct": -0.15}

THRESHOLDS = {"verde_min": 70, "amarillo_min": 50, "rojo_below": 50}

CLIMATE_TABLE = [
    {"max_mm": 5, "climate": 25},
    {"max_mm": 15, "climate": 45},
    {"max_mm": 25, "climate": 70},
    {"max_mm": 50, "climate": 90},
    {"max_mm": 80, "climate": 85},
    {"max_mm": None, "climate": 60},
]

CANON_VERSION = "precrop-canon-v1"

STAC_URL = "https://planetarycomputer.microsoft.com/api/stac/v1"
SCENE_CRS_EPSG = 32720  # UTM 20S -- both pinned scenes fall in this zone
EXPECTED_N_PIXELS = 10300  # 103 x 100 px @ 10 m over the AOI bbox
RAIN_TIMEZONE = "America/Argentina/Cordoba"

# --check tolerances. NDVI ±0.002 and rain ±0.2mm come from the design's
# cross-cutting table -- tighter than the spec's ±0.005 NDVI acceptance
# scenario (a stricter NDVI probe can only ever be at least as strict as
# the spec's, never looser), and looser than the spec's literal "rain
# reproduces exactly" (kept as a deliberate deviation: Open-Meteo's archive
# is ERA5-reanalysis-backed and can revise historical days by a fraction of
# a mm on re-fetch; an exact-equality gate would make `--check` flaky
# against a live upstream for a value that is not on the demo path at all).
CHECK_TOLERANCES = {"ndvi": 0.002, "rain_mm": 0.2}


# ---------------------------------------------------------------------------
# I/O helpers
# ---------------------------------------------------------------------------

def read_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def write_json(path: Path, obj: Any) -> None:
    """Write JSON with LF line endings, UTF-8, ensure_ascii=False, trailing newline.

    Windows CRLF would silently change every file's bytes and every git
    diff (see design cross-cutting rules) -- newline="\\n" pins LF
    regardless of the host OS's default.
    """
    text = json.dumps(obj, indent=2, ensure_ascii=False, sort_keys=False)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write(text + "\n")


# ---------------------------------------------------------------------------
# Canonicalisation - "precrop-canon-v1" (see SOURCES.md / design)
# ---------------------------------------------------------------------------

def _canon_number(value: Any) -> Any:
    """Normalise one payload value so Python and JS serialise it identically.

    Python's `json.dumps` writes an integral float as `100.0`; JS has no
    separate int/float number type, so `JSON.stringify` of the same
    abstract value always writes `100`. Left uncorrected, a scenario whose
    score happened to land on a whole number (or on `-0.0`) would hash
    differently in the Python producer and the TS/JS verifier -- exactly
    the kind of silent cross-language divergence T11/T10 exist to catch.
    `float.is_integer()` is True for `-0.0` too, and `int(-0.0) == 0`, so
    this single check folds both cases into one.
    """
    if isinstance(value, float) and value.is_integer():
        return int(value)
    return value


def canonicalize_payload(payload: Dict[str, Any]) -> str:
    """Serialise a FLAT payload per the precrop-canon-v1 rule.

    Keys sorted ascending by Unicode code point, no whitespace anywhere,
    UTF-8 bytes, ensure_ascii=False (payload values must already be
    ASCII-only strings so this never actually escapes anything). Integral
    floats and -0.0 are coerced to plain ints first -- see `_canon_number`.
    """
    normalised = {k: _canon_number(v) for k, v in payload.items()}
    return json.dumps(
        normalised,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    )


def hash_payload(payload: Dict[str, Any]) -> str:
    canonical = canonicalize_payload(payload)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# Scoring helpers (Front owns the formula; the pack only publishes it +
# applies it once to compute expected_score / the evidence report's score)
# ---------------------------------------------------------------------------

def climate_from_rain(rain_mm_7d: float) -> int:
    for rule in CLIMATE_TABLE:
        if rule["max_mm"] is None or rain_mm_7d < rule["max_mm"]:
            return rule["climate"]
    return CLIMATE_TABLE[-1]["climate"]


def ndvi_norm(ndvi: float) -> float:
    value = (ndvi - NDVI_FLOOR) / (NDVI_CEILING - NDVI_FLOOR) * 100
    return max(0.0, min(100.0, value))


def score_from_inputs(ndvi: float, rain_mm_7d: float, weeds_pct: float) -> float:
    n = ndvi_norm(ndvi)
    c = climate_from_rain(rain_mm_7d)
    return (
        WEIGHTS["ndvi_norm"] * n
        + WEIGHTS["climate"] * c
        + WEIGHTS["weeds_pct"] * weeds_pct
    )


def light_for_score(score: float) -> str:
    if score >= THRESHOLDS["verde_min"]:
        return "verde"
    if score >= THRESHOLDS["amarillo_min"]:
        return "amarillo"
    return "rojo"


def score_bp_from_score(score: float) -> int:
    """Integer basis points for Solidity: round HALF-UP, not Python's
    banker's rounding. Python's builtin `round()` rounds .5 ties to the
    nearest EVEN integer (round(0.5) == 0, round(1.5) == 2); JS's
    `Math.round()` always rounds .5 UP. `floor(x + 0.5)` matches Math.round
    for all our positive scores, so Chain's TS client reproduces the same
    integer from the same float without a special case.
    """
    return math.floor(score * 100 + 0.5)


def scene_timestamp_utc(scene_id: str) -> str:
    """Parse the acquisition instant out of a Sentinel-2 scene id.

    e.g. S2B_MSIL2A_20250202T140709_... -> "2025-02-02T14:07:09Z"
    """
    part = scene_id.split("_")[2]
    dt = datetime.strptime(part, "%Y%m%dT%H%M%S").replace(tzinfo=timezone.utc)
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


# ---------------------------------------------------------------------------
# Reproduction layer (Phase 4) -- pure helpers first (no network, no
# rasterio, covered by tests/test_build_pack.py), then the functions that
# actually hit STAC / Planetary Computer / Open-Meteo.
# ---------------------------------------------------------------------------

def ndvi_offset_for_baseline(processing_baseline: str) -> float:
    """BOA_ADD_OFFSET for a Sentinel-2 L2A processing baseline string.

    Baselines >= "04.00" shifted DN by +1000 (ESA's harmonisation change of
    2022-01-25), so BOA reflectance must subtract it back out: BOA = (DN -
    1000) / 10000. Earlier baselines need no correction. Zero-padded
    "NN.NN" strings compare correctly as plain strings.
    """
    return -1000.0 if processing_baseline >= "04.00" else 0.0


def percentile(values: list, pct: float) -> float:
    """Linear-interpolation percentile (matches numpy's default 'linear'
    method) over a list of numbers. `values` need not be pre-sorted.

    Pure Python so it is testable without numpy/rasterio, and is the same
    implementation `ndvi_stats` uses on the (flattened) raster window --
    there is only one percentile rule in this codebase, not a duplicated
    "test" one and a "real" one that could silently diverge.
    """
    ordered = sorted(values)
    n = len(ordered)
    if n == 1:
        return float(ordered[0])
    rank = (pct / 100.0) * (n - 1)
    lo = math.floor(rank)
    hi = math.ceil(rank)
    weight = rank - lo
    return float(ordered[lo] + (ordered[hi] - ordered[lo]) * weight)


def rain_window_dates(date: str) -> tuple:
    """(start, end) ISO date strings for the 7-day-inclusive rain window:
    the scene date plus the 6 previous days."""
    from datetime import date as date_cls, timedelta

    end = date_cls.fromisoformat(date)
    start = end - timedelta(days=6)
    return start.isoformat(), end.isoformat()


def fetch_scene(scene_id: str):
    """STAC search for exactly one Sentinel-2 L2A item, BY SCENE ID.

    Searching by id (not by a datetime window) is deterministic -- one
    request, one result, no pagination/truncation risk. Import is local so
    this module never requires pystac_client to be installed just to be
    imported (e.g. by pytest or --help).
    """
    import pystac_client

    catalog = pystac_client.Client.open(STAC_URL)
    items = list(catalog.search(collections=["sentinel-2-l2a"], ids=[scene_id]).items())
    if not items:
        raise RuntimeError(f"scene not found on STAC ({STAC_URL}): {scene_id}")
    return items[0]


def sign(item):
    """SAS-sign a STAC item's asset hrefs against Planetary Computer
    (anonymous, no API key needed). Import is local -- see module docstring.
    """
    import planetary_computer

    return planetary_computer.sign_item(item)


def ndvi_stats(item, bbox: list) -> Dict[str, Any]:
    """Offset-corrected NDVI stats over `bbox` (WGS84) for a signed item.

    Reads ONLY the AOI window from B04/B08 (never the whole scene), in the
    scene's own CRS (EPSG:32720 for both pinned scenes). Asserts the pixel
    count so a wrong bbox/CRS/resolution fails loudly instead of silently
    shipping a wrong stat.
    """
    import numpy as np
    import rasterio
    from rasterio.warp import transform_bounds
    from rasterio.windows import from_bounds

    baseline = item.properties.get("s2:processing_baseline", "00.00")
    offset = ndvi_offset_for_baseline(baseline)

    def read_window(asset_key: str):
        href = item.assets[asset_key].href
        with rasterio.open(href) as ds:
            if ds.crs.to_epsg() != SCENE_CRS_EPSG:
                raise RuntimeError(
                    f"unexpected scene CRS for {item.id}: EPSG:{ds.crs.to_epsg()} "
                    f"(expected EPSG:{SCENE_CRS_EPSG})"
                )
            left, bottom, right, top = transform_bounds("EPSG:4326", ds.crs, *bbox)
            window = from_bounds(left, bottom, right, top, transform=ds.transform)
            return ds.read(1, window=window).astype("float64")

    red_dn = read_window("B04")
    nir_dn = read_window("B08")

    boa_red = (red_dn + offset) / 10000.0
    boa_nir = (nir_dn + offset) / 10000.0
    denom = boa_nir + boa_red
    with np.errstate(invalid="ignore", divide="ignore"):
        ndvi = np.where(denom == 0, np.nan, (boa_nir - boa_red) / denom)

    valid = ndvi[~np.isnan(ndvi)].flatten().tolist()
    n_pixels = len(valid)
    assert n_pixels == EXPECTED_N_PIXELS, (
        f"expected {EXPECTED_N_PIXELS} pixels for {item.id}, got {n_pixels}"
    )

    return {
        "mean": sum(valid) / n_pixels,
        "median": statistics_median(valid),
        "p10": percentile(valid, 10),
        "p90": percentile(valid, 90),
        "n_pixels": n_pixels,
        "processing_baseline": baseline,
    }


def statistics_median(values: list) -> float:
    """Thin wrapper so ndvi_stats has one obvious import site; kept as a
    plain function (not inlined) so it is trivially mockable in tests."""
    from statistics import median

    return float(median(values))


def rain_7d(lat: float, lon: float, date: str) -> float:
    """Sum of Open-Meteo daily precipitation over the 7-day window ending
    on `date` (inclusive), rounded to 1 decimal. Import is local -- see
    module docstring."""
    import requests

    start, end = rain_window_dates(date)
    resp = requests.get(
        "https://archive-api.open-meteo.com/v1/archive",
        params={
            "latitude": lat,
            "longitude": lon,
            "start_date": start,
            "end_date": end,
            "daily": "precipitation_sum",
            "timezone": RAIN_TIMEZONE,
        },
        timeout=30,
    )
    resp.raise_for_status()
    daily = resp.json()["daily"]["precipitation_sum"]
    return round(sum(v for v in daily if v is not None), 1)


def recompute_measured() -> Dict[str, Dict[str, Any]]:
    """Recompute NDVI stats + 7-day rain for both live presets (fecha_buena,
    fecha_mala) from upstream APIs. Network + rasterio required -- call
    only from --write/--check/--only {ndvi,rain,assemble}."""
    presets = read_json(DATA_DIR / "lote-sentinel-presets.json")
    out: Dict[str, Dict[str, Any]] = {}
    for preset_key, scene_id in SCENES.items():
        preset = presets["presets"][preset_key]
        item = sign(fetch_scene(scene_id))
        out[preset_key] = {
            "ndvi_stats": ndvi_stats(item, AOI_BBOX),
            "rain_mm_7d": rain_7d(CENTER["lat"], CENTER["lon"], preset["date"]),
        }
    return out


# ---------------------------------------------------------------------------
# Evidence report assembly
# ---------------------------------------------------------------------------

def build_evidence(
    scenario_key: str,
    presets: Dict[str, Any],
    scenarios: Dict[str, Any],
    points: Dict[str, Any],
) -> Dict[str, Any]:
    """Assemble the flat, hashable evidence payload for one scenario.

    Reads the already-committed v2 pack files (each the single source of
    truth for its own inputs) rather than recomputing from raw upstream
    data -- the raw fetch/recompute path is this script's `--write` mode
    (later batch); this function's job is deterministic re-assembly.
    """
    scenario = scenarios["scenarios"][scenario_key]
    preset_key = scenario["satellite_preset"]
    preset = presets["presets"][preset_key]
    weeds_pct = points["scenarios"][scenario_key]["weeds_pct_lote"]

    score_exact = score_from_inputs(preset["ndvi"], preset["rain_mm_7d"], weeds_pct)
    light = light_for_score(score_exact)
    scene_id = preset["sentinel2"]["scene_id"]

    payload: Dict[str, Any] = {
        "cloud_cover_pct": preset["sentinel2"]["cloud_cover_pct"],
        "climate": climate_from_rain(preset["rain_mm_7d"]),
        "collection": preset["sentinel2"]["collection"],
        "evidence_timestamp_utc": scene_timestamp_utc(scene_id),
        "light": light,
        "lote_id": presets["lote_id"],
        "ndvi": preset["ndvi"],
        "ndvi_mean": preset["ndvi_stats"]["mean"],
        "ndvi_method": "BOA=(DN-1000)/10000; NDVI=(B08-B04)/(B08+B04)",
        "ndvi_p10": preset["ndvi_stats"]["p10"],
        "ndvi_p90": preset["ndvi_stats"]["p90"],
        "ndvi_norm": round(ndvi_norm(preset["ndvi"]), 4),
        "ndvi_source": preset["ndvi_source"],
        "ndvi_stat": "median",
        "n_pixels": preset["ndvi_stats"]["n_pixels"],
        "observed_date": preset["date"],
        "processing_baseline": preset["sentinel2"]["processing_baseline"],
        "rain_mm_7d": preset["rain_mm_7d"],
        "rain_source": preset["rain_source"],
        "rain_window_end": preset["rain_window"]["end"],
        "rain_window_start": preset["rain_window"]["start"],
        "scenario": scenario_key,
        "scene_id": scene_id,
        "score": round(score_exact, 4),
        "score_bp": score_bp_from_score(score_exact),
        "score_source": "computed_from_published_formula",
        "weeds_pct": weeds_pct,
        "weeds_source": "simulated",
    }
    return payload


def build_evidence_report(
    scenario_key: str,
    presets: Dict[str, Any],
    scenarios: Dict[str, Any],
    points: Dict[str, Any],
    report_id_suffix: str = "v1",
) -> Dict[str, Any]:
    payload = build_evidence(scenario_key, presets, scenarios, points)
    digest = hash_payload(payload)
    return {
        "schema_version": 1,
        "pack_version": presets.get("pack_version", "1.0.0"),
        "report_id": f"precrop-{presets['lote_id']}-{scenario_key}-{report_id_suffix}",
        "canonicalization": CANON_VERSION,
        "generated_at_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "content_sha256": digest,
        "payload": payload,
    }


def build_or_reuse_evidence_report(
    path: Path,
    scenario_key: str,
    presets: Dict[str, Any],
    scenarios: Dict[str, Any],
    points: Dict[str, Any],
) -> Dict[str, Any]:
    """Build the evidence report for `scenario_key`; if `path` already holds
    a report with an IDENTICAL `payload`, return that report UNCHANGED
    (same `generated_at_utc`, same bytes) instead of stamping a fresh
    timestamp. Without this, `--write` would rewrite every evidence file
    (and its `generated_at_utc`) on every run even when nothing about the
    scenario actually changed, making "regenerate and diff" always dirty.
    """
    payload = build_evidence(scenario_key, presets, scenarios, points)
    if path.exists():
        try:
            existing = read_json(path)
        except (OSError, json.JSONDecodeError):
            existing = None
        if existing is not None and existing.get("payload") == payload:
            return existing
    return build_evidence_report(scenario_key, presets, scenarios, points)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _load_pack_files():
    presets = read_json(DATA_DIR / "lote-sentinel-presets.json")
    scenarios = read_json(DATA_DIR / "demo-scenarios.json")
    points = read_json(DATA_DIR / "photo-point-presets.json")
    return presets, scenarios, points


def _cmd_evidence(write: bool) -> int:
    """Assemble (and optionally write) data/evidence/*.json from the
    already-committed pack files. Offline: no network, no rasterio."""
    presets, scenarios, points = _load_pack_files()
    for scenario_key in scenarios["scenarios"]:
        path = DATA_DIR / "evidence" / f"{scenario_key}.json"
        if write:
            report = build_or_reuse_evidence_report(path, scenario_key, presets, scenarios, points)
            write_json(path, report)
        else:
            report = build_evidence_report(scenario_key, presets, scenarios, points)
        p = report["payload"]
        print(
            f"{scenario_key}: score={p['score']} light={p['light']} "
            f"sha256={report['content_sha256']}"
        )
    return 0


def _cmd_ndvi() -> int:
    """--only ndvi: recompute + print NDVI stats for both live scenes.
    Read-only diagnostic; never writes."""
    for preset_key, scene_id in SCENES.items():
        try:
            stats = ndvi_stats(sign(fetch_scene(scene_id)), AOI_BBOX)
        except Exception as exc:  # network / STAC / rasterio unavailable
            print(f"{preset_key}: UNVERIFIED ({exc})")
            return 2
        print(
            f"{preset_key} ({scene_id}): mean={stats['mean']:.3f} "
            f"median={stats['median']:.3f} p10={stats['p10']:.3f} "
            f"p90={stats['p90']:.3f} n_pixels={stats['n_pixels']}"
        )
    return 0


def _cmd_rain() -> int:
    """--only rain: recompute + print the 7-day rain sum for both scenes'
    dates. Read-only diagnostic; never writes."""
    presets = read_json(DATA_DIR / "lote-sentinel-presets.json")
    for preset_key in SCENES:
        date = presets["presets"][preset_key]["date"]
        try:
            mm = rain_7d(CENTER["lat"], CENTER["lon"], date)
        except Exception as exc:  # network unavailable
            print(f"{preset_key}: UNVERIFIED ({exc})")
            return 2
        print(f"{preset_key} ({date}): rain_mm_7d={mm}")
    return 0


def _cmd_assemble() -> int:
    """--only assemble: recompute NDVI + rain for both scenes and print
    them side by side. Read-only diagnostic (use --write to persist)."""
    try:
        recomputed = recompute_measured()
    except Exception as exc:
        print(f"UNVERIFIED (offline or upstream unreachable): {exc}")
        return 2
    for preset_key, values in recomputed.items():
        stats = values["ndvi_stats"]
        print(
            f"{preset_key}: ndvi_median={stats['median']:.3f} "
            f"ndvi_mean={stats['mean']:.3f} rain_mm_7d={values['rain_mm_7d']}"
        )
    return 0


def _cmd_write() -> int:
    """Regenerate the measured fields in lote-sentinel-presets.json from
    upstream APIs, then rewrite the evidence reports from the refreshed
    presets. Refuses on a dirty presets file so a bad fetch can never
    silently clobber a committed, reviewed value."""
    import subprocess

    dirty = subprocess.run(
        ["git", "status", "--porcelain", "--", "data/lote-sentinel-presets.json"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if dirty.returncode == 0 and dirty.stdout.strip():
        print("refusing --write: data/lote-sentinel-presets.json has uncommitted changes")
        return 1

    try:
        recomputed = recompute_measured()
    except Exception as exc:
        print(f"UNVERIFIED (offline or upstream unreachable): {exc}")
        return 2

    presets = read_json(DATA_DIR / "lote-sentinel-presets.json")
    for preset_key in SCENES:
        preset = presets["presets"][preset_key]
        stats = recomputed[preset_key]["ndvi_stats"]
        preset["ndvi"] = round(stats["median"], 3)
        preset["ndvi_stats"] = {
            "mean": round(stats["mean"], 3),
            "median": round(stats["median"], 3),
            "p10": round(stats["p10"], 3),
            "p90": round(stats["p90"], 3),
            "n_pixels": stats["n_pixels"],
        }
        preset["rain_mm_7d"] = recomputed[preset_key]["rain_mm_7d"]
    write_json(DATA_DIR / "lote-sentinel-presets.json", presets)

    scenarios = read_json(DATA_DIR / "demo-scenarios.json")
    points = read_json(DATA_DIR / "photo-point-presets.json")
    for scenario_key in scenarios["scenarios"]:
        path = DATA_DIR / "evidence" / f"{scenario_key}.json"
        report = build_or_reuse_evidence_report(path, scenario_key, presets, scenarios, points)
        write_json(path, report)

    print("wrote data/lote-sentinel-presets.json and data/evidence/*.json")
    return 0


def _check_field(label: str, published: float, recomputed: float, tolerance: float) -> Dict[str, Any]:
    delta = round(recomputed - published, 6)
    return {
        "label": label,
        "published": published,
        "recomputed": round(recomputed, 6),
        "delta": delta,
        "ok": abs(delta) <= tolerance,
    }


def _cmd_check() -> int:
    """Recompute NDVI + rain from live STAC/Open-Meteo, compare to the
    committed pack values, write NOTHING.

    Exit codes: 0 match (within CHECK_TOLERANCES) - 1 mismatch (prints a
    per-field delta table) - 2 unverified (network/STAC/Open-Meteo
    unreachable; explicitly NOT a failure, so an offline demo-day run of
    this audit-only script does not look broken).
    """
    presets = read_json(DATA_DIR / "lote-sentinel-presets.json")

    try:
        recomputed = recompute_measured()
    except Exception as exc:
        print(f"UNVERIFIED (offline or upstream unreachable): {exc}")
        return 2

    rows = []
    for preset_key in SCENES:
        preset = presets["presets"][preset_key]
        stats = recomputed[preset_key]["ndvi_stats"]
        rows.append(_check_field(
            f"{preset_key}.ndvi_mean", preset["ndvi_stats"]["mean"], stats["mean"],
            CHECK_TOLERANCES["ndvi"],
        ))
        rows.append(_check_field(
            f"{preset_key}.ndvi_median", preset["ndvi_stats"]["median"], stats["median"],
            CHECK_TOLERANCES["ndvi"],
        ))
        rows.append(_check_field(
            f"{preset_key}.rain_mm_7d", preset["rain_mm_7d"], recomputed[preset_key]["rain_mm_7d"],
            CHECK_TOLERANCES["rain_mm"],
        ))

    print(f"{'field':<24}{'published':>12}{'recomputed':>12}{'delta':>10}  ok")
    for r in rows:
        print(f"{r['label']:<24}{r['published']:>12}{r['recomputed']:>12}{r['delta']:>10}  {r['ok']}")

    return 0 if all(r["ok"] for r in rows) else 1


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="PreCrop evidence pack build/audit tool. Audit-only: "
        "nothing on the demo path calls this script. There is no "
        "--fetch-photos mode -- preset photos are owned by another track."
    )
    parser.add_argument(
        "--only",
        choices=["ndvi", "rain", "assemble", "evidence"],
        default="evidence",
        help="Stage to run (default: evidence). ndvi/rain/assemble are "
        "read-only network diagnostics; evidence assembles (and, with "
        "--write, writes) data/evidence/*.json from the committed pack files.",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="Persist results. With --only evidence (default): write "
        "data/evidence/*.json from the committed presets (offline). With "
        "--only assemble: regenerate data/lote-sentinel-presets.json and "
        "data/evidence/*.json from upstream APIs (network required).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Recompute NDVI + rain from live STAC/Open-Meteo and compare "
        "to the committed values. Writes nothing. "
        "Exit 0 match, 1 mismatch, 2 unreachable/offline.",
    )
    args = parser.parse_args(argv)

    if args.check:
        return _cmd_check()

    if args.only == "ndvi":
        return _cmd_ndvi()
    if args.only == "rain":
        return _cmd_rain()
    if args.only == "assemble":
        return _cmd_write() if args.write else _cmd_assemble()
    return _cmd_evidence(write=args.write)


if __name__ == "__main__":
    raise SystemExit(main())
